name = "shipinku"
compatibility_date = "2026-05-18"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = "./build"

# 环境变量
[env.production.vars]
API_BASE_URL = "http://141.148.0.209:8080"

# 路由规则
[[routes]]
pattern = "901.555554.xyz/*"
custom_domain = true
